-- Companies
INSERT INTO filter (created_at, updated_at, filter_type, name)
VALUES (now(), now(), 'COMPANY', 'AM'),
       (now(), now(), 'COMPANY', 'BA'),
       (now(), now(), 'COMPANY', 'BG'),
       (now(), now(), 'COMPANY', 'BK'),
       (now(), now(), 'COMPANY', 'BN'),
       (now(), now(), 'COMPANY', 'BT'),
       (now(), now(), 'COMPANY', 'CB'),
       (now(), now(), 'COMPANY', 'CP'),
       (now(), now(), 'COMPANY', 'CS'),
       (now(), now(), 'COMPANY', 'CT'),
       (now(), now(), 'COMPANY', 'CU'),
       (now(), now(), 'COMPANY', 'DE'),
       (now(), now(), 'COMPANY', 'DG'),
       (now(), now(), 'COMPANY', 'DP'),
       (now(), now(), 'COMPANY', 'E0'),
       (now(), now(), 'COMPANY', 'EA'),
       (now(), now(), 'COMPANY', 'EC'),
       (now(), now(), 'COMPANY', 'EG'),
       (now(), now(), 'COMPANY', 'EH'),
       (now(), now(), 'COMPANY', 'EK'),
       (now(), now(), 'COMPANY', 'EM'),
       (now(), now(), 'COMPANY', 'EN'),
       (now(), now(), 'COMPANY', 'EP'),
       (now(), now(), 'COMPANY', 'EV'),
       (now(), now(), 'COMPANY', 'EZ'),
       (now(), now(), 'COMPANY', 'G1'),
       (now(), now(), 'COMPANY', 'G2'),
       (now(), now(), 'COMPANY', 'GN'),
       (now(), now(), 'COMPANY', 'GP'),
       (now(), now(), 'COMPANY', 'GS'),
       (now(), now(), 'COMPANY', 'HB'),
       (now(), now(), 'COMPANY', 'HD'),
       (now(), now(), 'COMPANY', 'HE'),
       (now(), now(), 'COMPANY', 'HL'),
       (now(), now(), 'COMPANY', 'HM'),
       (now(), now(), 'COMPANY', 'HS'),
       (now(), now(), 'COMPANY', 'HW'),
       (now(), now(), 'COMPANY', 'IK'),
       (now(), now(), 'COMPANY', 'JA'),
       (now(), now(), 'COMPANY', 'JC'),
       (now(), now(), 'COMPANY', 'JD'),
       (now(), now(), 'COMPANY', 'JE'),
       (now(), now(), 'COMPANY', 'JH'),
       (now(), now(), 'COMPANY', 'JJ'),
       (now(), now(), 'COMPANY', 'JN'),
       (now(), now(), 'COMPANY', 'JT'),
       (now(), now(), 'COMPANY', 'JU'),
       (now(), now(), 'COMPANY', 'KA'),
       (now(), now(), 'COMPANY', 'KC'),
       (now(), now(), 'COMPANY', 'KE'),
       (now(), now(), 'COMPANY', 'KI'),
       (now(), now(), 'COMPANY', 'KL'),
       (now(), now(), 'COMPANY', 'KM'),
       (now(), now(), 'COMPANY', 'KN'),
       (now(), now(), 'COMPANY', 'KO'),
       (now(), now(), 'COMPANY', 'KP'),
       (now(), now(), 'COMPANY', 'KS'),
       (now(), now(), 'COMPANY', 'KT'),
       (now(), now(), 'COMPANY', 'KU'),
       (now(), now(), 'COMPANY', 'LD'),
       (now(), now(), 'COMPANY', 'LH'),
       (now(), now(), 'COMPANY', 'MA'),
       (now(), now(), 'COMPANY', 'ME'),
       (now(), now(), 'COMPANY', 'MO'),
       (now(), now(), 'COMPANY', 'MT'),
       (now(), now(), 'COMPANY', 'NB'),
       (now(), now(), 'COMPANY', 'NE'),
       (now(), now(), 'COMPANY', 'NJ'),
       (now(), now(), 'COMPANY', 'NT'),
       (now(), now(), 'COMPANY', 'OB'),
       (now(), now(), 'COMPANY', 'PC'),
       (now(), now(), 'COMPANY', 'PI'),
       (now(), now(), 'COMPANY', 'PL'),
       (now(), now(), 'COMPANY', 'PS'),
       (now(), now(), 'COMPANY', 'PW'),
       (now(), now(), 'COMPANY', 'RE'),
       (now(), now(), 'COMPANY', 'S1'),
       (now(), now(), 'COMPANY', 'SA'),
       (now(), now(), 'COMPANY', 'SB'),
       (now(), now(), 'COMPANY', 'SC'),
       (now(), now(), 'COMPANY', 'SD'),
       (now(), now(), 'COMPANY', 'SE'),
       (now(), now(), 'COMPANY', 'SF'),
       (now(), now(), 'COMPANY', 'SG'),
       (now(), now(), 'COMPANY', 'SJ'),
       (now(), now(), 'COMPANY', 'SK'),
       (now(), now(), 'COMPANY', 'SM'),
       (now(), now(), 'COMPANY', 'SN'),
       (now(), now(), 'COMPANY', 'SO'),
       (now(), now(), 'COMPANY', 'SP'),
       (now(), now(), 'COMPANY', 'SR'),
       (now(), now(), 'COMPANY', 'SS'),
       (now(), now(), 'COMPANY', 'ST'),
       (now(), now(), 'COMPANY', 'TB'),
       (now(), now(), 'COMPANY', 'TD'),
       (now(), now(), 'COMPANY', 'TL'),
       (now(), now(), 'COMPANY', 'TM'),
       (now(), now(), 'COMPANY', 'UN'),
       (now(), now(), 'COMPANY', 'US'),
       (now(), now(), 'COMPANY', 'YY');


-- connectorType
INSERT INTO filter (created_at, updated_at, filter_type, name)
VALUES (now(), now(), 'CONNECTOR_TYPE', 'DC_FAST'),
       (now(), now(), 'CONNECTOR_TYPE', 'AC_SLOW'),
       (now(), now(), 'CONNECTOR_TYPE', 'DC_AC_3PHASE'),
       (now(), now(), 'CONNECTOR_TYPE', 'DC_COMBO'),
       (now(), now(), 'CONNECTOR_TYPE', 'DC_DC_COMBO'),
       (now(), now(), 'CONNECTOR_TYPE', 'DC_AC_DC_COMBO'),
       (now(), now(), 'CONNECTOR_TYPE', 'AC_3PHASE');

-- capacity
INSERT INTO filter (created_at, updated_at, filter_type, name)
VALUES (now(), now(), 'CAPACITY', '3'),
       (now(), now(), 'CAPACITY', '7'),
       (now(), now(), 'CAPACITY', '50'),
       (now(), now(), 'CAPACITY', '100'),
       (now(), now(), 'CAPACITY', '200');

INSERT INTO car (created_at, updated_at, name, vintage)
VALUES (now(), now(), '아이오닉5', '2023-Long Range'),
       (now(), now(), '기아 EV6', '2023-GT');

INSERT INTO car_filter (created_at, updated_at, car_id, filter_id)
VALUES (now(), now(), 1, 104), -- DC_COMBO
       (now(), now(), 2, 104); -- DC_COMBO
