-- Companies
INSERT INTO filter (created_at, updated_at, filter_type, name)
VALUES (now(), now(), 'company', 'AM'),
       (now(), now(), 'company', 'BA'),
       (now(), now(), 'company', 'BG'),
       (now(), now(), 'company', 'BK'),
       (now(), now(), 'company', 'BN'),
       (now(), now(), 'company', 'BT'),
       (now(), now(), 'company', 'CB'),
       (now(), now(), 'company', 'CP'),
       (now(), now(), 'company', 'CS'),
       (now(), now(), 'company', 'CT'),
       (now(), now(), 'company', 'CU'),
       (now(), now(), 'company', 'DE'),
       (now(), now(), 'company', 'DG'),
       (now(), now(), 'company', 'DP'),
       (now(), now(), 'company', 'E0'),
       (now(), now(), 'company', 'EA'),
       (now(), now(), 'company', 'EC'),
       (now(), now(), 'company', 'EG'),
       (now(), now(), 'company', 'EH'),
       (now(), now(), 'company', 'EK'),
       (now(), now(), 'company', 'EM'),
       (now(), now(), 'company', 'EN'),
       (now(), now(), 'company', 'EP'),
       (now(), now(), 'company', 'EV'),
       (now(), now(), 'company', 'EZ'),
       (now(), now(), 'company', 'G1'),
       (now(), now(), 'company', 'G2'),
       (now(), now(), 'company', 'GN'),
       (now(), now(), 'company', 'GP'),
       (now(), now(), 'company', 'GS'),
       (now(), now(), 'company', 'HB'),
       (now(), now(), 'company', 'HD'),
       (now(), now(), 'company', 'HE'),
       (now(), now(), 'company', 'HL'),
       (now(), now(), 'company', 'HM'),
       (now(), now(), 'company', 'HS'),
       (now(), now(), 'company', 'HW'),
       (now(), now(), 'company', 'IK'),
       (now(), now(), 'company', 'JA'),
       (now(), now(), 'company', 'JC'),
       (now(), now(), 'company', 'JD'),
       (now(), now(), 'company', 'JE'),
       (now(), now(), 'company', 'JH'),
       (now(), now(), 'company', 'JJ'),
       (now(), now(), 'company', 'JN'),
       (now(), now(), 'company', 'JT'),
       (now(), now(), 'company', 'JU'),
       (now(), now(), 'company', 'KA'),
       (now(), now(), 'company', 'KC'),
       (now(), now(), 'company', 'KE'),
       (now(), now(), 'company', 'KI'),
       (now(), now(), 'company', 'KL'),
       (now(), now(), 'company', 'KM'),
       (now(), now(), 'company', 'KN'),
       (now(), now(), 'company', 'KO'),
       (now(), now(), 'company', 'KP'),
       (now(), now(), 'company', 'KS'),
       (now(), now(), 'company', 'KT'),
       (now(), now(), 'company', 'KU'),
       (now(), now(), 'company', 'LD'),
       (now(), now(), 'company', 'LH'),
       (now(), now(), 'company', 'MA'),
       (now(), now(), 'company', 'ME'),
       (now(), now(), 'company', 'MO'),
       (now(), now(), 'company', 'MT'),
       (now(), now(), 'company', 'NB'),
       (now(), now(), 'company', 'NE'),
       (now(), now(), 'company', 'NJ'),
       (now(), now(), 'company', 'NT'),
       (now(), now(), 'company', 'OB'),
       (now(), now(), 'company', 'PC'),
       (now(), now(), 'company', 'PI'),
       (now(), now(), 'company', 'PL'),
       (now(), now(), 'company', 'PS'),
       (now(), now(), 'company', 'PW'),
       (now(), now(), 'company', 'RE'),
       (now(), now(), 'company', 'S1'),
       (now(), now(), 'company', 'SA'),
       (now(), now(), 'company', 'SB'),
       (now(), now(), 'company', 'SC'),
       (now(), now(), 'company', 'SD'),
       (now(), now(), 'company', 'SE'),
       (now(), now(), 'company', 'SF'),
       (now(), now(), 'company', 'SG'),
       (now(), now(), 'company', 'SJ'),
       (now(), now(), 'company', 'SK'),
       (now(), now(), 'company', 'SM'),
       (now(), now(), 'company', 'SN'),
       (now(), now(), 'company', 'SO'),
       (now(), now(), 'company', 'SP'),
       (now(), now(), 'company', 'SR'),
       (now(), now(), 'company', 'SS'),
       (now(), now(), 'company', 'ST'),
       (now(), now(), 'company', 'TB'),
       (now(), now(), 'company', 'TD'),
       (now(), now(), 'company', 'TL'),
       (now(), now(), 'company', 'TM'),
       (now(), now(), 'company', 'UN'),
       (now(), now(), 'company', 'US'),
       (now(), now(), 'company', 'YY');


-- connectorType
INSERT INTO filter (created_at, updated_at, filter_type, name)
VALUES (now(), now(), 'connectorType', 'DC_FAST'),
       (now(), now(), 'connectorType', 'AC_SLOW'),
       (now(), now(), 'connectorType', 'DC_AC_3PHASE'),
       (now(), now(), 'connectorType', 'DC_COMBO'),
       (now(), now(), 'connectorType', 'DC_DC_COMBO'),
       (now(), now(), 'connectorType', 'DC_AC_DC_COMBO'),
       (now(), now(), 'connectorType', 'AC_3PHASE');

-- capacity
INSERT INTO filter (created_at, updated_at, filter_type, name)
VALUES (now(), now(), 'capacity', '3'),
       (now(), now(), 'capacity', '7'),
       (now(), now(), 'capacity', '50'),
       (now(), now(), 'capacity', '100'),
       (now(), now(), 'capacity', '200');

INSERT INTO car (created_at, updated_at, name, vintage)
VALUES (now(), now(), '아이오닉5', '2023-Long Range'),
       (now(), now(), '기아 EV6', '2023-GT');

INSERT INTO car_filter (created_at, updated_at, car_id, filter_id)
VALUES (now(), now(), 1, 104), -- DC_COMBO
       (now(), now(), 2, 104); -- DC_COMBO
