spring:
  datasource:
    source:
      jdbc-url: ENC(5hPDpp1tSTx3G6S4IEfZslkV0AtSL7cPoC7ObNUPSHns3ZK3NJnsl6G5LL4MijtcJQQMQ8FalcIb2tt9UKpIme5oQlp2tZWUpK8TISZQ5xmdDP7mnV+3vbga8/6WLU++BDP+VThl7lGD7g6cSv+9xv1nrHXgDUHaPSAkTavlPPQETgoTfN+x6Yovyn+uR6Sgt4ESq1RfgOn6oatzc2PHieHI+SKDuUPrERmjsNSFmqY=)
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      jdbc-url: ENC(gKg3SpXLQBc1s3saZvuz4268urCevwbfdjsxDtpjEgnrzjD/R2W1fUSsMVCWLy5S2zmtLfgXTOIoLGWNNzinaIahPea2tkD9z4qrhlfFVJjZG1k5BZCw8nVEa0Vqlo6BeQPpy+adR34oDoemcy/6ZcOFGU0v9Sgke9LavJsUzatIHHqk3/8vvNdHhRA1sx/d4J7bYvf00xCgElllboYatCqOursU1w15x53O/TgpaA5ky6O03gKBVw==)
      username: ${REPLICA_DATABASE_USERNAME}
      password: ${REPLICA_DATABASE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

initialize-city:
  enabled: true

initialize-charge:
  enabled: false

scheduling:
  enabled: false
