package com.carffeine.carffeine.dto;

public record ChargeStationInfoRequest(
	String trafficYn,
	String delDetail,
	String delYn,
	String limitDetail,
	String limitYn,
	String note,
	String parkingFree,
	String kindDetail,
	String kind,
	String zscode,
	String zcode,
	String method,
	String output,
	String powerType,
	String nowTsdt,
	String lastTedt,
	String lastTsdt,
	String statUpdDt,
	String stat,
	String busiCall,
	String busiNm,
	String bnm,
	String busiId,
	String lng,
	String lat,
	String useTime,
	String location,
	String addr,
	String chgerType,
	String chgerId,
	String statId,
	String statNm
) {
}
