name: backend-test

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  test:
    name: merge-when-test
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew build
