name: storybook-deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3

      - name: Set up Node 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm build
        run: npm run build-storybook

      - name: Upload frontend build file to artifact
        uses: actions/upload-artifact@v3
        with:
          name: FrontendApplication
          path: frontend/storybook-static

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
#      - name: Remove previous version app
#        working-directory: frontend/dev/
#        run: rm -rf dist

      - name: Download build file from artifact
        uses: actions/download-artifact@v3
        with:
          name: FrontendApplication
          path: frontend/dev/dist

      - name: Deploy to WAS
        working-directory: frontend/dev/
        run: |
          cp -r ./dist /home/ubuntu
