name: storybook-deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm build
        run: npm run build-storybook

  deploy:
    needs: build-and-upload
    runs-on: self-hosted
    steps:
#      - name: Remove previous version app
#        working-directory: ./frontend/dev/
#        run: rm -rf dist

      - name: Download build file from artifact
        uses: actions/download-artifact@v3
        with:
          name: FrontendApplication
          path: frontend/dev/dist

#      - name: Deploy to WAS
#        working-directory: ./frontend/dev/
#        run: |
