name: storybook-deploy

on:
  push:
    branches:
      - develop
    paths:
      - frontend/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: storybook build
        run: npm run build-storybook
